using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace StudentManagement.Desktop.Forms
{
    partial class frmFeeCollection
    {
        private IContainer components = null;
        private Label lblTitle;
        private Panel pnlSearch;
        private TextBox txtSearch;
        private Button btnFind;
        private Panel pnlBio;
        private Label lblBioName;
        private Label lblBioReg;
        private Label lblBioClass;
        private Label lblBioDue;
        private Label lblBioPhone;
        private Panel pnlMatrix;
        private Label lblMonths;
        private FlowLayoutPanel flpMonths;
        private Panel pnlOtherFees;
        private Label lblOtherFees;
        private Label lblRegistrationFee;
        private TextBox txtRegistrationFee;
        private Label lblAdmissionFee;
        private TextBox txtAdmissionFee;
        private Label lblTransportFee;
        private TextBox txtTransportFee;
        private Label lblExaminationFee;
        private TextBox txtExaminationFee;
        private Label lblTranscriptFee;
        private TextBox txtTranscriptFee;
        private Label lblTransferCertificateFee;
        private TextBox txtTransferCertificateFee;
        private Label lblHostelFoodCharges;
        private TextBox txtHostelFoodCharges;
        private Label lblMiscellaneous;
        private TextBox txtMiscellaneous;
        private Panel pnlPay;
        private Label lblUnitTuition;
        private TextBox txtTuitionUnit;
        private Label lblFine;
        private TextBox txtFine;
        private Label lblWaiver;
        private TextBox txtWaiver;
        private Label lblPayMethod;
        private ComboBox cboPaymentMethod;
        private Label lblTxnRef;
        private TextBox txtTxnRef;
        private Label lblRemarks;
        private TextBox txtRemarks;
        private Label lblTuitionTotal;
        private Label lblNetPayable;
        private Button btnCollect;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.lblTitle = new System.Windows.Forms.Label();
            this.pnlSearch = new System.Windows.Forms.Panel();
            this.txtSearch = new System.Windows.Forms.TextBox();
            this.btnFind = new System.Windows.Forms.Button();
            this.pnlBio = new System.Windows.Forms.Panel();
            this.lblBioName = new System.Windows.Forms.Label();
            this.lblBioReg = new System.Windows.Forms.Label();
            this.lblBioClass = new System.Windows.Forms.Label();
            this.lblBioPhone = new System.Windows.Forms.Label();
            this.lblBioDue = new System.Windows.Forms.Label();
            this.pnlMatrix = new System.Windows.Forms.Panel();
            this.lblMonths = new System.Windows.Forms.Label();
            this.flpMonths = new System.Windows.Forms.FlowLayoutPanel();
            this.pnlOtherFees = new System.Windows.Forms.Panel();
            this.lblOtherFees = new System.Windows.Forms.Label();
            this.lblRegistrationFee = new System.Windows.Forms.Label();
            this.txtRegistrationFee = new System.Windows.Forms.TextBox();
            this.lblAdmissionFee = new System.Windows.Forms.Label();
            this.txtAdmissionFee = new System.Windows.Forms.TextBox();
            this.lblTransportFee = new System.Windows.Forms.Label();
            this.txtTransportFee = new System.Windows.Forms.TextBox();
            this.lblExaminationFee = new System.Windows.Forms.Label();
            this.txtExaminationFee = new System.Windows.Forms.TextBox();
            this.lblTranscriptFee = new System.Windows.Forms.Label();
            this.txtTranscriptFee = new System.Windows.Forms.TextBox();
            this.lblTransferCertificateFee = new System.Windows.Forms.Label();
            this.txtTransferCertificateFee = new System.Windows.Forms.TextBox();
            this.lblHostelFoodCharges = new System.Windows.Forms.Label();
            this.txtHostelFoodCharges = new System.Windows.Forms.TextBox();
            this.lblMiscellaneous = new System.Windows.Forms.Label();
            this.txtMiscellaneous = new System.Windows.Forms.TextBox();
            this.pnlPay = new System.Windows.Forms.Panel();
            this.lblUnitTuition = new System.Windows.Forms.Label();
            this.txtTuitionUnit = new System.Windows.Forms.TextBox();
            this.lblFine = new System.Windows.Forms.Label();
            this.txtFine = new System.Windows.Forms.TextBox();
            this.lblWaiver = new System.Windows.Forms.Label();
            this.txtWaiver = new System.Windows.Forms.TextBox();
            this.lblPayMethod = new System.Windows.Forms.Label();
            this.cboPaymentMethod = new System.Windows.Forms.ComboBox();
            this.lblTxnRef = new System.Windows.Forms.Label();
            this.txtTxnRef = new System.Windows.Forms.TextBox();
            this.lblRemarks = new System.Windows.Forms.Label();
            this.txtRemarks = new System.Windows.Forms.TextBox();
            this.lblTuitionTotal = new System.Windows.Forms.Label();
            this.lblNetPayable = new System.Windows.Forms.Label();
            this.btnCollect = new System.Windows.Forms.Button();
            this.pnlSearch.SuspendLayout();
            this.pnlBio.SuspendLayout();
            this.pnlMatrix.SuspendLayout();
            this.pnlOtherFees.SuspendLayout();
            this.pnlPay.SuspendLayout();
            this.SuspendLayout();
            // lblTitle
            this.lblTitle.AutoSize = true;
            this.lblTitle.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold);
            this.lblTitle.ForeColor = System.Drawing.Color.White;
            this.lblTitle.Location = new System.Drawing.Point(16, 12);
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.Size = new System.Drawing.Size(200, 25);
            this.lblTitle.TabIndex = 0;
            this.lblTitle.Text = "Fee Collection Counter";
            // pnlSearch
            this.pnlSearch.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(13)))), ((int)(((byte)(20)))), ((int)(((byte)(48)))));
            this.pnlSearch.Controls.Add(this.txtSearch);
            this.pnlSearch.Controls.Add(this.btnFind);
            this.pnlSearch.Location = new System.Drawing.Point(16, 50);
            this.pnlSearch.Name = "pnlSearch";
            this.pnlSearch.Size = new System.Drawing.Size(960, 60);
            this.pnlSearch.TabIndex = 1;
            this.pnlSearch.Tag = "card";
            // txtSearch
            this.txtSearch.Location = new System.Drawing.Point(16, 16);
            this.txtSearch.Name = "txtSearch";
            this.txtSearch.Size = new System.Drawing.Size(360, 23);
            this.txtSearch.TabIndex = 0;
            // btnFind
            this.btnFind.Location = new System.Drawing.Point(400, 12);
            this.btnFind.Name = "btnFind";
            this.btnFind.Size = new System.Drawing.Size(130, 34);
            this.btnFind.TabIndex = 1;
            this.btnFind.Text = "Quick Search";
            this.btnFind.Click += new System.EventHandler(this.btnFind_Click);
            // pnlBio
            this.pnlBio.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(13)))), ((int)(((byte)(20)))), ((int)(((byte)(48)))));
            this.pnlBio.Controls.Add(this.lblBioName);
            this.pnlBio.Controls.Add(this.lblBioReg);
            this.pnlBio.Controls.Add(this.lblBioClass);
            this.pnlBio.Controls.Add(this.lblBioPhone);
            this.pnlBio.Controls.Add(this.lblBioDue);
            this.pnlBio.Location = new System.Drawing.Point(16, 124);
            this.pnlBio.Name = "pnlBio";
            this.pnlBio.Size = new System.Drawing.Size(960, 100);
            this.pnlBio.TabIndex = 2;
            this.pnlBio.Tag = "card";
            this.lblBioName.AutoSize = true;
            this.lblBioName.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold);
            this.lblBioName.ForeColor = System.Drawing.Color.White;
            this.lblBioName.Location = new System.Drawing.Point(16, 12);
            this.lblBioName.Name = "lblBioName";
            this.lblBioName.Size = new System.Drawing.Size(20, 25);
            this.lblBioName.TabIndex = 0;
            this.lblBioName.Text = "-";
            this.lblBioReg.AutoSize = true;
            this.lblBioReg.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(147)))), ((int)(((byte)(166)))));
            this.lblBioReg.Location = new System.Drawing.Point(16, 48);
            this.lblBioReg.Name = "lblBioReg";
            this.lblBioReg.Size = new System.Drawing.Size(12, 15);
            this.lblBioReg.TabIndex = 1;
            this.lblBioReg.Text = "-";
            this.lblBioClass.AutoSize = true;
            this.lblBioClass.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(147)))), ((int)(((byte)(166)))));
            this.lblBioClass.Location = new System.Drawing.Point(220, 48);
            this.lblBioClass.Name = "lblBioClass";
            this.lblBioClass.Size = new System.Drawing.Size(12, 15);
            this.lblBioClass.TabIndex = 2;
            this.lblBioClass.Text = "-";
            this.lblBioPhone.AutoSize = true;
            this.lblBioPhone.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(147)))), ((int)(((byte)(166)))));
            this.lblBioPhone.Location = new System.Drawing.Point(520, 48);
            this.lblBioPhone.Name = "lblBioPhone";
            this.lblBioPhone.Size = new System.Drawing.Size(12, 15);
            this.lblBioPhone.TabIndex = 3;
            this.lblBioPhone.Text = "-";
            this.lblBioDue.AutoSize = true;
            this.lblBioDue.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.lblBioDue.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(63)))), ((int)(((byte)(94)))));
            this.lblBioDue.Location = new System.Drawing.Point(720, 20);
            this.lblBioDue.Name = "lblBioDue";
            this.lblBioDue.Size = new System.Drawing.Size(12, 19);
            this.lblBioDue.TabIndex = 4;
            this.lblBioDue.Text = "-";
            // pnlMatrix
            this.pnlMatrix.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(13)))), ((int)(((byte)(20)))), ((int)(((byte)(48)))));
            this.pnlMatrix.Controls.Add(this.lblMonths);
            this.pnlMatrix.Controls.Add(this.flpMonths);
            this.pnlMatrix.Location = new System.Drawing.Point(16, 240);
            this.pnlMatrix.Name = "pnlMatrix";
            this.pnlMatrix.Size = new System.Drawing.Size(960, 140);
            this.pnlMatrix.TabIndex = 3;
            this.pnlMatrix.Tag = "card";
            this.lblMonths.AutoSize = true;
            this.lblMonths.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.lblMonths.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(147)))), ((int)(((byte)(166)))));
            this.lblMonths.Location = new System.Drawing.Point(16, 10);
            this.lblMonths.Name = "lblMonths";
            this.lblMonths.Size = new System.Drawing.Size(120, 19);
            this.lblMonths.TabIndex = 0;
            this.lblMonths.Text = "Tuition Fee Months";
            this.flpMonths.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(13)))), ((int)(((byte)(20)))), ((int)(((byte)(48)))));
            this.flpMonths.Location = new System.Drawing.Point(8, 36);
            this.flpMonths.Name = "flpMonths";
            this.flpMonths.Size = new System.Drawing.Size(940, 90);
            this.flpMonths.TabIndex = 1;
            // pnlOtherFees — same label-above-textbox style as Unit Tuition / Fine
            this.pnlOtherFees.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(13)))), ((int)(((byte)(20)))), ((int)(((byte)(48)))));
            this.pnlOtherFees.Controls.Add(this.lblOtherFees);
            this.pnlOtherFees.Controls.Add(this.lblRegistrationFee);
            this.pnlOtherFees.Controls.Add(this.txtRegistrationFee);
            this.pnlOtherFees.Controls.Add(this.lblAdmissionFee);
            this.pnlOtherFees.Controls.Add(this.txtAdmissionFee);
            this.pnlOtherFees.Controls.Add(this.lblTransportFee);
            this.pnlOtherFees.Controls.Add(this.txtTransportFee);
            this.pnlOtherFees.Controls.Add(this.lblExaminationFee);
            this.pnlOtherFees.Controls.Add(this.txtExaminationFee);
            this.pnlOtherFees.Controls.Add(this.lblTranscriptFee);
            this.pnlOtherFees.Controls.Add(this.txtTranscriptFee);
            this.pnlOtherFees.Controls.Add(this.lblTransferCertificateFee);
            this.pnlOtherFees.Controls.Add(this.txtTransferCertificateFee);
            this.pnlOtherFees.Controls.Add(this.lblHostelFoodCharges);
            this.pnlOtherFees.Controls.Add(this.txtHostelFoodCharges);
            this.pnlOtherFees.Controls.Add(this.lblMiscellaneous);
            this.pnlOtherFees.Controls.Add(this.txtMiscellaneous);
            this.pnlOtherFees.Location = new System.Drawing.Point(16, 396);
            this.pnlOtherFees.Name = "pnlOtherFees";
            this.pnlOtherFees.Size = new System.Drawing.Size(960, 200);
            this.pnlOtherFees.TabIndex = 4;
            this.pnlOtherFees.Tag = "card";
            this.lblOtherFees.AutoSize = true;
            this.lblOtherFees.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.lblOtherFees.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(147)))), ((int)(((byte)(166)))));
            this.lblOtherFees.Location = new System.Drawing.Point(16, 10);
            this.lblOtherFees.Name = "lblOtherFees";
            this.lblOtherFees.Size = new System.Drawing.Size(280, 19);
            this.lblOtherFees.TabIndex = 0;
            this.lblOtherFees.Text = "Optional Fees (fill only if needed)";
            // Row 1
            this.lblRegistrationFee.AutoSize = true;
            this.lblRegistrationFee.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(147)))), ((int)(((byte)(166)))));
            this.lblRegistrationFee.Location = new System.Drawing.Point(16, 40);
            this.lblRegistrationFee.Name = "lblRegistrationFee";
            this.lblRegistrationFee.Size = new System.Drawing.Size(100, 15);
            this.lblRegistrationFee.TabIndex = 1;
            this.lblRegistrationFee.Text = "Registration Fee";
            this.txtRegistrationFee.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(24)))), ((int)(((byte)(39)))));
            this.txtRegistrationFee.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtRegistrationFee.ForeColor = System.Drawing.Color.White;
            this.txtRegistrationFee.Location = new System.Drawing.Point(16, 60);
            this.txtRegistrationFee.Name = "txtRegistrationFee";
            this.txtRegistrationFee.Size = new System.Drawing.Size(220, 23);
            this.txtRegistrationFee.TabIndex = 2;
            this.txtRegistrationFee.Text = "0";
            this.lblAdmissionFee.AutoSize = true;
            this.lblAdmissionFee.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(147)))), ((int)(((byte)(166)))));
            this.lblAdmissionFee.Location = new System.Drawing.Point(252, 40);
            this.lblAdmissionFee.Name = "lblAdmissionFee";
            this.lblAdmissionFee.Size = new System.Drawing.Size(160, 15);
            this.lblAdmissionFee.TabIndex = 3;
            this.lblAdmissionFee.Text = "New Admission / Re-admission";
            this.txtAdmissionFee.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(24)))), ((int)(((byte)(39)))));
            this.txtAdmissionFee.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtAdmissionFee.ForeColor = System.Drawing.Color.White;
            this.txtAdmissionFee.Location = new System.Drawing.Point(252, 60);
            this.txtAdmissionFee.Name = "txtAdmissionFee";
            this.txtAdmissionFee.Size = new System.Drawing.Size(220, 23);
            this.txtAdmissionFee.TabIndex = 4;
            this.txtAdmissionFee.Text = "0";
            this.lblTransportFee.AutoSize = true;
            this.lblTransportFee.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(147)))), ((int)(((byte)(166)))));
            this.lblTransportFee.Location = new System.Drawing.Point(488, 40);
            this.lblTransportFee.Name = "lblTransportFee";
            this.lblTransportFee.Size = new System.Drawing.Size(130, 15);
            this.lblTransportFee.TabIndex = 5;
            this.lblTransportFee.Text = "Monthly Transport Fee";
            this.txtTransportFee.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(24)))), ((int)(((byte)(39)))));
            this.txtTransportFee.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtTransportFee.ForeColor = System.Drawing.Color.White;
            this.txtTransportFee.Location = new System.Drawing.Point(488, 60);
            this.txtTransportFee.Name = "txtTransportFee";
            this.txtTransportFee.Size = new System.Drawing.Size(220, 23);
            this.txtTransportFee.TabIndex = 6;
            this.txtTransportFee.Text = "0";
            this.lblExaminationFee.AutoSize = true;
            this.lblExaminationFee.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(147)))), ((int)(((byte)(166)))));
            this.lblExaminationFee.Location = new System.Drawing.Point(724, 40);
            this.lblExaminationFee.Name = "lblExaminationFee";
            this.lblExaminationFee.Size = new System.Drawing.Size(200, 15);
            this.lblExaminationFee.TabIndex = 7;
            this.lblExaminationFee.Text = "Examination Fee (Term / Annual)";
            this.txtExaminationFee.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(24)))), ((int)(((byte)(39)))));
            this.txtExaminationFee.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtExaminationFee.ForeColor = System.Drawing.Color.White;
            this.txtExaminationFee.Location = new System.Drawing.Point(724, 60);
            this.txtExaminationFee.Name = "txtExaminationFee";
            this.txtExaminationFee.Size = new System.Drawing.Size(220, 23);
            this.txtExaminationFee.TabIndex = 8;
            this.txtExaminationFee.Text = "0";
            // Row 2
            this.lblTranscriptFee.AutoSize = true;
            this.lblTranscriptFee.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(147)))), ((int)(((byte)(166)))));
            this.lblTranscriptFee.Location = new System.Drawing.Point(16, 100);
            this.lblTranscriptFee.Name = "lblTranscriptFee";
            this.lblTranscriptFee.Size = new System.Drawing.Size(200, 15);
            this.lblTranscriptFee.TabIndex = 9;
            this.lblTranscriptFee.Text = "Transcript / Testimonial / Certificate";
            this.txtTranscriptFee.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(24)))), ((int)(((byte)(39)))));
            this.txtTranscriptFee.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtTranscriptFee.ForeColor = System.Drawing.Color.White;
            this.txtTranscriptFee.Location = new System.Drawing.Point(16, 120);
            this.txtTranscriptFee.Name = "txtTranscriptFee";
            this.txtTranscriptFee.Size = new System.Drawing.Size(220, 23);
            this.txtTranscriptFee.TabIndex = 10;
            this.txtTranscriptFee.Text = "0";
            this.lblTransferCertificateFee.AutoSize = true;
            this.lblTransferCertificateFee.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(147)))), ((int)(((byte)(166)))));
            this.lblTransferCertificateFee.Location = new System.Drawing.Point(252, 100);
            this.lblTransferCertificateFee.Name = "lblTransferCertificateFee";
            this.lblTransferCertificateFee.Size = new System.Drawing.Size(200, 15);
            this.lblTransferCertificateFee.TabIndex = 11;
            this.lblTransferCertificateFee.Text = "Transfer Certificate / Letter";
            this.txtTransferCertificateFee.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(24)))), ((int)(((byte)(39)))));
            this.txtTransferCertificateFee.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtTransferCertificateFee.ForeColor = System.Drawing.Color.White;
            this.txtTransferCertificateFee.Location = new System.Drawing.Point(252, 120);
            this.txtTransferCertificateFee.Name = "txtTransferCertificateFee";
            this.txtTransferCertificateFee.Size = new System.Drawing.Size(220, 23);
            this.txtTransferCertificateFee.TabIndex = 12;
            this.txtTransferCertificateFee.Text = "0";
            this.lblHostelFoodCharges.AutoSize = true;
            this.lblHostelFoodCharges.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(147)))), ((int)(((byte)(166)))));
            this.lblHostelFoodCharges.Location = new System.Drawing.Point(488, 100);
            this.lblHostelFoodCharges.Name = "lblHostelFoodCharges";
            this.lblHostelFoodCharges.Size = new System.Drawing.Size(120, 15);
            this.lblHostelFoodCharges.TabIndex = 13;
            this.lblHostelFoodCharges.Text = "Hostel Food Charges";
            this.txtHostelFoodCharges.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(24)))), ((int)(((byte)(39)))));
            this.txtHostelFoodCharges.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtHostelFoodCharges.ForeColor = System.Drawing.Color.White;
            this.txtHostelFoodCharges.Location = new System.Drawing.Point(488, 120);
            this.txtHostelFoodCharges.Name = "txtHostelFoodCharges";
            this.txtHostelFoodCharges.Size = new System.Drawing.Size(220, 23);
            this.txtHostelFoodCharges.TabIndex = 14;
            this.txtHostelFoodCharges.Text = "0";
            this.lblMiscellaneous.AutoSize = true;
            this.lblMiscellaneous.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(147)))), ((int)(((byte)(166)))));
            this.lblMiscellaneous.Location = new System.Drawing.Point(724, 100);
            this.lblMiscellaneous.Name = "lblMiscellaneous";
            this.lblMiscellaneous.Size = new System.Drawing.Size(80, 15);
            this.lblMiscellaneous.TabIndex = 15;
            this.lblMiscellaneous.Text = "Miscellaneous";
            this.txtMiscellaneous.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(24)))), ((int)(((byte)(39)))));
            this.txtMiscellaneous.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtMiscellaneous.ForeColor = System.Drawing.Color.White;
            this.txtMiscellaneous.Location = new System.Drawing.Point(724, 120);
            this.txtMiscellaneous.Name = "txtMiscellaneous";
            this.txtMiscellaneous.Size = new System.Drawing.Size(220, 23);
            this.txtMiscellaneous.TabIndex = 16;
            this.txtMiscellaneous.Text = "0";
            // pnlPay
            this.pnlPay.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(13)))), ((int)(((byte)(20)))), ((int)(((byte)(48)))));
            this.pnlPay.Controls.Add(this.lblUnitTuition);
            this.pnlPay.Controls.Add(this.txtTuitionUnit);
            this.pnlPay.Controls.Add(this.lblFine);
            this.pnlPay.Controls.Add(this.txtFine);
            this.pnlPay.Controls.Add(this.lblWaiver);
            this.pnlPay.Controls.Add(this.txtWaiver);
            this.pnlPay.Controls.Add(this.lblPayMethod);
            this.pnlPay.Controls.Add(this.cboPaymentMethod);
            this.pnlPay.Controls.Add(this.lblTxnRef);
            this.pnlPay.Controls.Add(this.txtTxnRef);
            this.pnlPay.Controls.Add(this.lblRemarks);
            this.pnlPay.Controls.Add(this.txtRemarks);
            this.pnlPay.Controls.Add(this.lblTuitionTotal);
            this.pnlPay.Controls.Add(this.lblNetPayable);
            this.pnlPay.Controls.Add(this.btnCollect);
            this.pnlPay.Location = new System.Drawing.Point(16, 612);
            this.pnlPay.Name = "pnlPay";
            this.pnlPay.Size = new System.Drawing.Size(960, 180);
            this.pnlPay.TabIndex = 5;
            this.pnlPay.Tag = "card";
            this.lblUnitTuition.AutoSize = true;
            this.lblUnitTuition.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(147)))), ((int)(((byte)(166)))));
            this.lblUnitTuition.Location = new System.Drawing.Point(16, 16);
            this.lblUnitTuition.Name = "lblUnitTuition";
            this.lblUnitTuition.Size = new System.Drawing.Size(90, 15);
            this.lblUnitTuition.TabIndex = 0;
            this.lblUnitTuition.Text = "Unit Tuition";
            this.txtTuitionUnit.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(24)))), ((int)(((byte)(39)))));
            this.txtTuitionUnit.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtTuitionUnit.ForeColor = System.Drawing.Color.White;
            this.txtTuitionUnit.Location = new System.Drawing.Point(16, 36);
            this.txtTuitionUnit.Name = "txtTuitionUnit";
            this.txtTuitionUnit.Size = new System.Drawing.Size(120, 23);
            this.txtTuitionUnit.TabIndex = 1;
            this.txtTuitionUnit.Text = "0";
            this.lblFine.AutoSize = true;
            this.lblFine.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(147)))), ((int)(((byte)(166)))));
            this.lblFine.Location = new System.Drawing.Point(160, 16);
            this.lblFine.Name = "lblFine";
            this.lblFine.Size = new System.Drawing.Size(30, 15);
            this.lblFine.TabIndex = 2;
            this.lblFine.Text = "Fine";
            this.txtFine.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(24)))), ((int)(((byte)(39)))));
            this.txtFine.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtFine.ForeColor = System.Drawing.Color.White;
            this.txtFine.Location = new System.Drawing.Point(160, 36);
            this.txtFine.Name = "txtFine";
            this.txtFine.Size = new System.Drawing.Size(100, 23);
            this.txtFine.TabIndex = 3;
            this.txtFine.Text = "0";
            this.lblWaiver.AutoSize = true;
            this.lblWaiver.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(147)))), ((int)(((byte)(166)))));
            this.lblWaiver.Location = new System.Drawing.Point(280, 16);
            this.lblWaiver.Name = "lblWaiver";
            this.lblWaiver.Size = new System.Drawing.Size(45, 15);
            this.lblWaiver.TabIndex = 4;
            this.lblWaiver.Text = "Waiver";
            this.txtWaiver.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(24)))), ((int)(((byte)(39)))));
            this.txtWaiver.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtWaiver.ForeColor = System.Drawing.Color.White;
            this.txtWaiver.Location = new System.Drawing.Point(280, 36);
            this.txtWaiver.Name = "txtWaiver";
            this.txtWaiver.Size = new System.Drawing.Size(100, 23);
            this.txtWaiver.TabIndex = 5;
            this.txtWaiver.Text = "0";
            this.lblPayMethod.AutoSize = true;
            this.lblPayMethod.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(147)))), ((int)(((byte)(166)))));
            this.lblPayMethod.Location = new System.Drawing.Point(400, 16);
            this.lblPayMethod.Name = "lblPayMethod";
            this.lblPayMethod.Size = new System.Drawing.Size(100, 15);
            this.lblPayMethod.TabIndex = 6;
            this.lblPayMethod.Text = "Payment Method";
            this.cboPaymentMethod.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboPaymentMethod.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cboPaymentMethod.Location = new System.Drawing.Point(400, 36);
            this.cboPaymentMethod.Name = "cboPaymentMethod";
            this.cboPaymentMethod.Size = new System.Drawing.Size(160, 23);
            this.cboPaymentMethod.TabIndex = 7;
            this.lblTxnRef.AutoSize = true;
            this.lblTxnRef.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(147)))), ((int)(((byte)(166)))));
            this.lblTxnRef.Location = new System.Drawing.Point(580, 16);
            this.lblTxnRef.Name = "lblTxnRef";
            this.lblTxnRef.Size = new System.Drawing.Size(50, 15);
            this.lblTxnRef.TabIndex = 8;
            this.lblTxnRef.Text = "Txn Ref";
            this.txtTxnRef.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(24)))), ((int)(((byte)(39)))));
            this.txtTxnRef.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtTxnRef.ForeColor = System.Drawing.Color.White;
            this.txtTxnRef.Location = new System.Drawing.Point(580, 36);
            this.txtTxnRef.Name = "txtTxnRef";
            this.txtTxnRef.Size = new System.Drawing.Size(160, 23);
            this.txtTxnRef.TabIndex = 9;
            this.lblRemarks.AutoSize = true;
            this.lblRemarks.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(147)))), ((int)(((byte)(166)))));
            this.lblRemarks.Location = new System.Drawing.Point(16, 80);
            this.lblRemarks.Name = "lblRemarks";
            this.lblRemarks.Size = new System.Drawing.Size(55, 15);
            this.lblRemarks.TabIndex = 10;
            this.lblRemarks.Text = "Remarks";
            this.txtRemarks.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(24)))), ((int)(((byte)(39)))));
            this.txtRemarks.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtRemarks.ForeColor = System.Drawing.Color.White;
            this.txtRemarks.Location = new System.Drawing.Point(16, 100);
            this.txtRemarks.Name = "txtRemarks";
            this.txtRemarks.Size = new System.Drawing.Size(400, 23);
            this.txtRemarks.TabIndex = 11;
            this.lblTuitionTotal.AutoSize = true;
            this.lblTuitionTotal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(147)))), ((int)(((byte)(166)))));
            this.lblTuitionTotal.Location = new System.Drawing.Point(450, 100);
            this.lblTuitionTotal.Name = "lblTuitionTotal";
            this.lblTuitionTotal.Size = new System.Drawing.Size(80, 15);
            this.lblTuitionTotal.TabIndex = 12;
            this.lblTuitionTotal.Text = "Tuition: 0.00";
            this.lblNetPayable.AutoSize = true;
            this.lblNetPayable.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold);
            this.lblNetPayable.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(185)))), ((int)(((byte)(129)))));
            this.lblNetPayable.Location = new System.Drawing.Point(650, 90);
            this.lblNetPayable.Name = "lblNetPayable";
            this.lblNetPayable.Size = new System.Drawing.Size(70, 32);
            this.lblNetPayable.TabIndex = 13;
            this.lblNetPayable.Text = "0.00";
            this.btnCollect.Location = new System.Drawing.Point(750, 130);
            this.btnCollect.Name = "btnCollect";
            this.btnCollect.Size = new System.Drawing.Size(180, 36);
            this.btnCollect.TabIndex = 14;
            this.btnCollect.Tag = "success";
            this.btnCollect.Text = "Collect & Print Receipt";
            this.btnCollect.Click += new System.EventHandler(this.btnCollect_Click);
            // form
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoScroll = true;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(12)))), ((int)(((byte)(23)))));
            this.ClientSize = new System.Drawing.Size(1000, 820);
            this.Controls.Add(this.lblTitle);
            this.Controls.Add(this.pnlSearch);
            this.Controls.Add(this.pnlBio);
            this.Controls.Add(this.pnlMatrix);
            this.Controls.Add(this.pnlOtherFees);
            this.Controls.Add(this.pnlPay);
            this.Name = "frmFeeCollection";
            this.Text = "Fee Collection";
            this.pnlSearch.ResumeLayout(false);
            this.pnlSearch.PerformLayout();
            this.pnlBio.ResumeLayout(false);
            this.pnlBio.PerformLayout();
            this.pnlMatrix.ResumeLayout(false);
            this.pnlMatrix.PerformLayout();
            this.pnlOtherFees.ResumeLayout(false);
            this.pnlOtherFees.PerformLayout();
            this.pnlPay.ResumeLayout(false);
            this.pnlPay.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
